### ISSUE TITLE
Watch Later/History Give "No Entries Found"

### ISSUE THREAD

**Issue by MeanLauraJean** [Helza/YouTubeTV.bundle#3]
A new issue I started seeing yesterday - the Watch Later/History/Like Videos areas all show "No Entries Found". This was working up until very recently.

**Comment by Helza** [comment]
I've shortly looked into the problem but didn't have much time for it.
I seem to be unable to find the concrete location where its going wrong. I know the data is received for the subscriptons for example but unable to find the exact location in the code what is causing the plugin to stop working.
Unfortunatly ran out of time yesterday.

**Comment by Helza** [comment]
I pushed the changes @timangus made, who rewrote the subscriptions feed. 
Plugin should work again with those changes.

**Comment by MeanLauraJean** [comment]
This latest version has completely removed access to Watch Later/History/Liked Videos. The original issue was that these were not working (but the links were still available). Now the links themselves are completely gone. Could you please bring these back? It's the whole reason I logged this issue :) Thanks!

**Comment by timangus** [comment]
Liked videos are still there, but the other two options are gone. This is because Google has removed access to them from the YouTube API. All is not lost however; you can fake "Watch Later" by creating your own (private) playlist and using that as a substitute (playlists are still accessible.) "Watch History" is gone though :(.

**Comment by MeanLauraJean** [comment]
Thanks @timangus! We also still have access to Favorites under My channel. So I'm using that in order to "bookmark" videos. Thanks so much for your work on this! Will you also look into the issue with live feeds no longer playing?

**Comment by MeanLauraJean** [comment]
Closing based on last response from @timangus
